server:
  port: 19091

spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/orders/**

        - id: product
          uri: lb://product
          predicates:
            - Path=/api/products/**

        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**

      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/